# Generated by Django 3.0.8 on 2020-11-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201125_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplepack',
            old_name='desciption',
            new_name='description',
        ),
    ]
